// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flow.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusType int32

const (
	StatusType_OK    StatusType = 0
	StatusType_ERROR StatusType = 1
)

var StatusType_name = map[int32]string{
	0: "OK",
	1: "ERROR",
}

var StatusType_value = map[string]int32{
	"OK":    0,
	"ERROR": 1,
}

func (x StatusType) String() string {
	return proto.EnumName(StatusType_name, int32(x))
}

func (StatusType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{0}
}

type ProviderType int32

const (
	ProviderType_MASTER   ProviderType = 0
	ProviderType_EXECUTOR ProviderType = 1
	ProviderType_AGENT    ProviderType = 2
	ProviderType_GATEWAY  ProviderType = 3
)

var ProviderType_name = map[int32]string{
	0: "MASTER",
	1: "EXECUTOR",
	2: "AGENT",
	3: "GATEWAY",
}

var ProviderType_value = map[string]int32{
	"MASTER":   0,
	"EXECUTOR": 1,
	"AGENT":    2,
	"GATEWAY":  3,
}

func (x ProviderType) String() string {
	return proto.EnumName(ProviderType_name, int32(x))
}

func (ProviderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{1}
}

type SimulatorType int32

const (
	SimulatorType_RVO2 SimulatorType = 0
	SimulatorType_SUMO SimulatorType = 1
)

var SimulatorType_name = map[int32]string{
	0: "RVO2",
	1: "SUMO",
}

var SimulatorType_value = map[string]int32{
	"RVO2": 0,
	"SUMO": 1,
}

func (x SimulatorType) String() string {
	return proto.EnumName(SimulatorType_name, int32(x))
}

func (SimulatorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{2}
}

type AgentType int32

const (
	AgentType_PERSON AgentType = 0
	AgentType_CAR    AgentType = 1
)

var AgentType_name = map[int32]string{
	0: "PERSON",
	1: "CAR",
}

var AgentType_value = map[string]int32{
	"PERSON": 0,
	"CAR":    1,
}

func (x AgentType) String() string {
	return proto.EnumName(AgentType_name, int32(x))
}

func (AgentType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{3}
}

type MsgType int32

const (
	MsgType_SET_AGENT_REQUEST MsgType = 0
)

var MsgType_name = map[int32]string{
	0: "SET_AGENT_REQUEST",
}

var MsgType_value = map[string]int32{
	"SET_AGENT_REQUEST": 0,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{4}
}

type Agent struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 AgentType `protobuf:"varint,3,opt,name=type,proto3,enum=api.AgentType" json:"type,omitempty"`
	Position             *Vector   `protobuf:"bytes,4,opt,name=position,proto3" json:"position,omitempty"`
	Velocity             *Vector   `protobuf:"bytes,5,opt,name=velocity,proto3" json:"velocity,omitempty"`
	Route                *Route    `protobuf:"bytes,6,opt,name=route,proto3" json:"route,omitempty"`
	Data                 string    `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{0}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetType() AgentType {
	if m != nil {
		return m.Type
	}
	return AgentType_PERSON
}

func (m *Agent) GetPosition() *Vector {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *Agent) GetVelocity() *Vector {
	if m != nil {
		return m.Velocity
	}
	return nil
}

func (m *Agent) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

func (m *Agent) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Route struct {
	TransitPoints        []*TransitPoint `protobuf:"bytes,1,rep,name=transit_points,json=transitPoints,proto3" json:"transit_points,omitempty"`
	NextTransit          *TransitPoint   `protobuf:"bytes,2,opt,name=next_transit,json=nextTransit,proto3" json:"next_transit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{1}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetTransitPoints() []*TransitPoint {
	if m != nil {
		return m.TransitPoints
	}
	return nil
}

func (m *Route) GetNextTransit() *TransitPoint {
	if m != nil {
		return m.NextTransit
	}
	return nil
}

type TransitPoint struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Point                *Vector  `protobuf:"bytes,3,opt,name=point,proto3" json:"point,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransitPoint) Reset()         { *m = TransitPoint{} }
func (m *TransitPoint) String() string { return proto.CompactTextString(m) }
func (*TransitPoint) ProtoMessage()    {}
func (*TransitPoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{2}
}

func (m *TransitPoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransitPoint.Unmarshal(m, b)
}
func (m *TransitPoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransitPoint.Marshal(b, m, deterministic)
}
func (m *TransitPoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransitPoint.Merge(m, src)
}
func (m *TransitPoint) XXX_Size() int {
	return xxx_messageInfo_TransitPoint.Size(m)
}
func (m *TransitPoint) XXX_DiscardUnknown() {
	xxx_messageInfo_TransitPoint.DiscardUnknown(m)
}

var xxx_messageInfo_TransitPoint proto.InternalMessageInfo

func (m *TransitPoint) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TransitPoint) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TransitPoint) GetPoint() *Vector {
	if m != nil {
		return m.Point
	}
	return nil
}

type Vector struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vector) Reset()         { *m = Vector{} }
func (m *Vector) String() string { return proto.CompactTextString(m) }
func (*Vector) ProtoMessage()    {}
func (*Vector) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{3}
}

func (m *Vector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vector.Unmarshal(m, b)
}
func (m *Vector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vector.Marshal(b, m, deterministic)
}
func (m *Vector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vector.Merge(m, src)
}
func (m *Vector) XXX_Size() int {
	return xxx_messageInfo_Vector.Size(m)
}
func (m *Vector) XXX_DiscardUnknown() {
	xxx_messageInfo_Vector.DiscardUnknown(m)
}

var xxx_messageInfo_Vector proto.InternalMessageInfo

func (m *Vector) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Vector) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

type Provider struct {
	Id                   uint64       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 ProviderType `protobuf:"varint,2,opt,name=type,proto3,enum=api.ProviderType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{4}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Provider) GetType() ProviderType {
	if m != nil {
		return m.Type
	}
	return ProviderType_MASTER
}

type FlowMsg struct {
	MsgId                uint64   `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	SenderId             uint64   `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Type                 MsgType  `protobuf:"varint,3,opt,name=type,proto3,enum=api.MsgType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FlowMsg) Reset()         { *m = FlowMsg{} }
func (m *FlowMsg) String() string { return proto.CompactTextString(m) }
func (*FlowMsg) ProtoMessage()    {}
func (*FlowMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_bb3fc33c49933823, []int{5}
}

func (m *FlowMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FlowMsg.Unmarshal(m, b)
}
func (m *FlowMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FlowMsg.Marshal(b, m, deterministic)
}
func (m *FlowMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FlowMsg.Merge(m, src)
}
func (m *FlowMsg) XXX_Size() int {
	return xxx_messageInfo_FlowMsg.Size(m)
}
func (m *FlowMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_FlowMsg.DiscardUnknown(m)
}

var xxx_messageInfo_FlowMsg proto.InternalMessageInfo

func (m *FlowMsg) GetMsgId() uint64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *FlowMsg) GetSenderId() uint64 {
	if m != nil {
		return m.SenderId
	}
	return 0
}

func (m *FlowMsg) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_SET_AGENT_REQUEST
}

func init() {
	proto.RegisterEnum("api.StatusType", StatusType_name, StatusType_value)
	proto.RegisterEnum("api.ProviderType", ProviderType_name, ProviderType_value)
	proto.RegisterEnum("api.SimulatorType", SimulatorType_name, SimulatorType_value)
	proto.RegisterEnum("api.AgentType", AgentType_name, AgentType_value)
	proto.RegisterEnum("api.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Agent)(nil), "api.Agent")
	proto.RegisterType((*Route)(nil), "api.Route")
	proto.RegisterType((*TransitPoint)(nil), "api.TransitPoint")
	proto.RegisterType((*Vector)(nil), "api.Vector")
	proto.RegisterType((*Provider)(nil), "api.Provider")
	proto.RegisterType((*FlowMsg)(nil), "api.FlowMsg")
}

func init() { proto.RegisterFile("flow.proto", fileDescriptor_bb3fc33c49933823) }

var fileDescriptor_bb3fc33c49933823 = []byte{
	// 522 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0xcd, 0x3a, 0xb1, 0x93, 0x4c, 0xdc, 0xc8, 0x5d, 0xa9, 0xc8, 0x12, 0x07, 0x8c, 0x01, 0x11,
	0xe5, 0xd0, 0x43, 0xe0, 0xc0, 0x11, 0x53, 0x99, 0xaa, 0x42, 0x69, 0xc2, 0xda, 0x29, 0x94, 0x8b,
	0x65, 0x6a, 0x13, 0xad, 0x94, 0x78, 0x2d, 0xef, 0xa6, 0x49, 0xbe, 0x94, 0xdf, 0x41, 0x3b, 0x76,
	0xd3, 0x00, 0xbd, 0xed, 0xbc, 0xf7, 0x66, 0xde, 0xec, 0xcc, 0x2e, 0xc0, 0xaf, 0x95, 0xd8, 0x9e,
	0x97, 0x95, 0x50, 0x82, 0xb6, 0xd3, 0x92, 0xfb, 0xbf, 0x09, 0x98, 0xc1, 0x32, 0x2f, 0x14, 0x1d,
	0x82, 0xc1, 0x33, 0x97, 0x78, 0x64, 0xd4, 0x67, 0x06, 0xcf, 0x28, 0x85, 0x4e, 0x91, 0xae, 0x73,
	0xd7, 0x40, 0x04, 0xcf, 0xd4, 0x87, 0x8e, 0xda, 0x97, 0xb9, 0xdb, 0xf6, 0xc8, 0x68, 0x38, 0x19,
	0x9e, 0xa7, 0x25, 0x3f, 0xc7, 0xec, 0x78, 0x5f, 0xe6, 0x0c, 0x39, 0xfa, 0x16, 0x7a, 0xa5, 0x90,
	0x5c, 0x71, 0x51, 0xb8, 0x1d, 0x8f, 0x8c, 0x06, 0x93, 0x01, 0xea, 0x6e, 0xf2, 0x3b, 0x25, 0x2a,
	0x76, 0x20, 0xb5, 0xf0, 0x3e, 0x5f, 0x89, 0x3b, 0xae, 0xf6, 0xae, 0xf9, 0x84, 0xf0, 0x81, 0xa4,
	0x1e, 0x98, 0x95, 0xd8, 0xa8, 0xdc, 0xb5, 0x50, 0x05, 0xa8, 0x62, 0x1a, 0x61, 0x35, 0xa1, 0x7b,
	0xcd, 0x52, 0x95, 0xba, 0xdd, 0xba, 0x57, 0x7d, 0xf6, 0xb7, 0x60, 0xa2, 0x86, 0x7e, 0x80, 0xa1,
	0xaa, 0xd2, 0x42, 0x72, 0x95, 0x94, 0x82, 0x17, 0x4a, 0xba, 0xc4, 0x6b, 0x8f, 0x06, 0x93, 0x53,
	0xac, 0x13, 0xd7, 0xd4, 0x5c, 0x33, 0xec, 0x44, 0x1d, 0x45, 0x92, 0xbe, 0x07, 0xbb, 0xc8, 0x77,
	0x2a, 0x69, 0x50, 0x1c, 0xc5, 0x93, 0x79, 0x03, 0x2d, 0x6b, 0x10, 0xff, 0x16, 0xec, 0x63, 0xf2,
	0xbf, 0xc1, 0x3e, 0x03, 0x4b, 0xaa, 0x54, 0x6d, 0x64, 0x33, 0xda, 0x26, 0xa2, 0x2f, 0xc1, 0xc4,
	0xfe, 0x70, 0xba, 0xff, 0x0c, 0xa3, 0x66, 0xfc, 0xd7, 0x60, 0xd5, 0x00, 0xb5, 0x81, 0xec, 0xb0,
	0x26, 0x61, 0x64, 0xa7, 0xa3, 0x3d, 0x56, 0x23, 0x8c, 0xec, 0xfd, 0x00, 0x7a, 0xf3, 0x4a, 0xdc,
	0xf3, 0x2c, 0xaf, 0x8e, 0xcc, 0x3b, 0x68, 0xfe, 0xa6, 0xd9, 0xa0, 0x81, 0x1b, 0xac, 0xaf, 0xf2,
	0x20, 0x7e, 0x5c, 0xa2, 0x9f, 0x40, 0xf7, 0xf3, 0x4a, 0x6c, 0xa7, 0x72, 0x49, 0xcf, 0xc0, 0x5a,
	0xcb, 0x65, 0x72, 0xa8, 0x62, 0xae, 0xe5, 0xf2, 0x2a, 0xa3, 0xcf, 0xa1, 0x2f, 0xf3, 0x22, 0xcb,
	0x2b, 0xcd, 0x18, 0xc8, 0xf4, 0x6a, 0xe0, 0x2a, 0xa3, 0xde, 0x5f, 0xef, 0xc4, 0x46, 0x97, 0xa9,
	0x5c, 0x3e, 0x1a, 0x8c, 0x5f, 0x00, 0x44, 0x78, 0x6d, 0x8d, 0x51, 0x0b, 0x8c, 0xd9, 0x17, 0xa7,
	0x45, 0xfb, 0x60, 0x86, 0x8c, 0xcd, 0x98, 0x43, 0xc6, 0x1f, 0xc1, 0x3e, 0xee, 0x8b, 0x02, 0x58,
	0xd3, 0x20, 0x8a, 0x43, 0xe6, 0xb4, 0xa8, 0x0d, 0xbd, 0xf0, 0x7b, 0x78, 0xb1, 0x88, 0xb5, 0x52,
	0x27, 0x05, 0x97, 0xe1, 0x75, 0xec, 0x18, 0x74, 0x00, 0xdd, 0xcb, 0x20, 0x0e, 0xbf, 0x05, 0xb7,
	0x4e, 0x7b, 0xfc, 0x0a, 0x4e, 0x22, 0xbe, 0xde, 0xac, 0x52, 0x25, 0xea, 0x12, 0x3d, 0xe8, 0xb0,
	0x9b, 0xd9, 0xc4, 0x69, 0xe9, 0x53, 0xb4, 0x98, 0xce, 0x1c, 0x32, 0xf6, 0xa0, 0x7f, 0x78, 0xc0,
	0xda, 0x63, 0x1e, 0xb2, 0x68, 0x76, 0xed, 0xb4, 0x68, 0x17, 0xda, 0x17, 0x01, 0x43, 0x45, 0xb7,
	0x69, 0x9d, 0x9e, 0xc1, 0x69, 0x14, 0xc6, 0x09, 0xba, 0x25, 0x2c, 0xfc, 0xba, 0x08, 0xa3, 0xd8,
	0x69, 0x7d, 0x32, 0x7f, 0xe8, 0xaf, 0xf4, 0xd3, 0xc2, 0x6f, 0xf5, 0xee, 0x4f, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x07, 0xb2, 0xf4, 0xe7, 0x64, 0x03, 0x00, 0x00,
}
